// <auto-generated />
using FundooRepos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FundooRepos.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Models.UserModels.UserModel", b =>
                {
                    b.Property<string>("USERID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CARDTYPE");

                    b.Property<string>("PASSWORD")
                        .IsRequired();

                    b.Property<string>("USERNAME")
                        .IsRequired();

                    b.HasKey("USERID");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
